browsers:
  - name: chrome
    version:
      - 49 # último suportado no xp
      - -1..latest
  - name: firefox
    version:
      - 52 # suporte estendido
      - -1..latest
  - name: safari
    version: -1..latest
  - name: ie
    version: 9..latest
sauce_connect: true
loopback: airtap.local